### ISSUE TITLE
Log error when Controller quits

### ISSUE THREAD

**Issue by jstewart99** [FlyingDiver/Indigo-miniUniFi#19]
Updated the Controller (i.e. quit the app temporarily) and noticed this in the Log.  Confirmed issue happens if Controller quits.

Oct 28, 2020 at 8:55:43 AM
   miniUniFi Error                 Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 96, in runConcurrentThread
  File "plugin.py", line 210, in updateUniFiController
  File "plugin.py", line 186, in is_unifi_os
  File "/Library/Application Support/Perceptive Automation/Indigo 7/IndigoPluginHost.app/Contents/PlugIns/requests/api.py", line 97, in head
  File "/Library/Application Support/Perceptive Automation/Indigo 7/IndigoPluginHost.app/Contents/PlugIns/requests/api.py", line 57, in request
  File "/Library/Application Support/Perceptive Automation/Indigo 7/IndigoPluginHost.app/Contents/PlugIns/requests/sessions.py", line 477, in request
  File "/Library/Application Support/Perceptive Automation/Indigo 7/IndigoPluginHost.app/Contents/PlugIns/requests/sessions.py", line 587, in send
  File "/Library/Application Support/Perceptive Automation/Indigo 7/IndigoPluginHost.app/Contents/PlugIns/requests/adapters.py", line 481, in send
ConnectionError: HTTPSConnectionPool(host='192.168.0.69', port=8443): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x107b5bd90>: Failed to establish a new connection: [Errno 61] Connection refused',))

   miniUniFi Error                 plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)

**Comment by FlyingDiver** [comment]
So the controller was not running when he plugin attempted contact it?  I can trap that.

**Comment by FlyingDiver** [comment]
Fix will be in 0.0.13.
