### ISSUE TITLE
Won't connect to UDM

### ISSUE THREAD

**Issue by Busta999** [FlyingDiver/Indigo-miniUniFi#8]
OK Ran into an issue

Code:
2020-10-24 15:38:43.920 miniUniFi Error Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
File "plugin.py", line 85, in runConcurrentThread
File "plugin.py", line 186, in updateUniFiController
File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 520, in post
File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 477, in request
File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 587, in send
File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/adapters.py", line 491, in send
SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:590)

2020-10-24 15:38:43.920 miniUniFi Error plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)

Checked IP/ Port Username and Password - copy and pasting username and password from login screen for Unifi

Username in my instance is NOT Admin if that makes any difference?

**Comment by FlyingDiver** [comment]
What MacOS version is your Indigo server running?  And then you connect to the controller in a browser, that URL do you use?

**Comment by Busta999** [comment]
Sierra

**Comment by Busta999** [comment]
192.168.1.1

**Comment by FlyingDiver** [comment]
> 192.168.1.1

That's an IP address, not a URL.  I assume you meant "https://192.168.1.1'?

That's normally a router address.  Is this a UniFi Dream Machine?

The real problem, however, is that Python on Sierra can't do SSL with current protocols.  The only real way to fix that is to upgrade to at least High Sierra.

**Comment by Busta999** [comment]
Sorry doing this on a phone on the run :-)

Yes https://192.168.1.1:8843

Yes my UDM 

Ok will upgrade to High Sierra - I had been hesitating due to usb driver issues and indigo

**Comment by FlyingDiver** [comment]
OK, reopen or start a new issue if the upgrade doesn't fix it.

**Comment by Busta999** [comment]
Ok will do
